import Link from "next/link";
import corpus from "../../../data/corpus.json";
import SearchBox from "../components/SearchBox";

const paragraphCount = corpus.reduce((sum, work) => sum + work.paragraphs.length, 0);

export default function Home() {
  return <main className="shell">
    <header className="hero"><p className="eyebrow">OPEN BUDDHIST DIGITAL KNOWLEDGE</p><h1>Digital Dhamma Library</h1><p className="lead">Read, search, study, and research Buddhist texts through stable, source-aware digital records.</p><SearchBox /><div className="actions"><Link className="button primary" href="/read/mn10/">Open MN 10</Link><Link className="button" href="/search/">Research search</Link><Link className="button" href="/dictionary/">Dictionary</Link><Link className="button" href="/works/">Works</Link><Link className="button" href="/sources/">Sources</Link><Link className="button" href="/research/">Research Workbench</Link><Link className="button" href="/occurrences/">Lemma search</Link><Link className="button" href="/review/">Review queue</Link><Link className="button" href="#library">Explore library</Link></div></header>
    <section id="library" className="section"><div className="section-heading"><div><p className="eyebrow">PHASE 2.2 RESEARCH ENGINE</p><h2>Available records</h2></div><span className="badge">{corpus.length} works · {paragraphCount} paragraphs</span></div><div className="grid">{corpus.map((work) => <Link className="card" href={`/read/${work.id}/`} key={work.id}><span className="card-kicker">{work.collection}</span><h3>{work.title}</h3><p>{work.description}</p><span className="card-link">Read →</span></Link>)}</div></section>
    <section className="section feature-grid"><article className="feature-card"><span className="feature-number">01</span><h3>Research search</h3><p>Search Pāḷi, English, বাংলা, metadata, phrases, collections, types, and languages.</p></article><article className="feature-card"><span className="feature-number">02</span><h3>Reader controls</h3><p>Toggle languages, adjust text size and line spacing, and keep stable paragraph anchors.</p></article><article className="feature-card"><span className="feature-number">03</span><h3>Source-aware data</h3><p>Every starter record carries edition and provenance notes so later licensed imports can be audited.</p></article><article className="feature-card"><span className="feature-number">04</span><h3>Research engine</h3><p>Edition witnesses, translation alignment, dictionary, morphology, occurrence, review, cross-reference, and citation layers are modeled as separate research resources.</p></article></section>
    <section className="section"><div className="notice"><strong>Phase 2.2:</strong> The Research Workbench now exposes edition-witness metadata, sentence-level alignment review, richer morphology provenance, citation profiles, and browser-local research review tools alongside the Phase 2 research foundations.<br /><br /><strong>Data principle:</strong> the expanded corpus is a structured research starter dataset. It is not presented as a complete critical edition; source editions and redistribution rights must be verified before any future public data release.</div></section>
  </main>;
}
